### ISSUE TITLE
Invalid repository URL error after clicking Deploy to Azure button

### ISSUE THREAD

**Issue by richstep** [microsoft/HealthBotContainerSample#68] opened 2020-04-15 18:20 UTC
![Annotation 2020-04-15 142017](https://user-images.githubusercontent.com/733563/79373181-4ae08600-7f24-11ea-818e-36569d4cd6d4.png)

**Comment by amir-microsoft** [comment] 2020-04-16 05:29
Hello @richstep 
This issue doesn't reproduce on our end.
Can you please provide the following details:
1. Which version of edge are you using
2. which branch are you triggering the deployment from - please provide a screenshot of the previous screen, before you click the "Deploy to Azure" button

**Comment by theonlybs** [comment] 2020-04-20 13:17
I'm seeing the same error on the chromium-based Edge browser, however, it's working in legacy Edge.

I'm on the Dev channel of chromium Edge, Version 83.0.478.5 (Official build) dev (64-bit)

**Comment by amir-microsoft** [comment] 2020-04-25 06:57
Closing this issue since the required details were not provided by the issue reporter

**Closed by amir-microsoft** 2020-04-25 06:57 UTC
